server:
  port: 9081
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xwsoft/easyspringcloud
          username: xiawensoft@126.com
          password: xwsoft1984
          basedir: /config_manage