server:
  port: 8000
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xwsoft/easyspringcloud
          username:
          password:
          basedir: /config_manage